"""Initial tables

Revision ID: c86405d6ebfd
Revises:
Create Date: 2026-07-03 11:48:22.885368

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c86405d6ebfd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "watch_tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("origin_iata", sa.String(length=3), nullable=False),
        sa.Column("destination_iata", sa.String(length=3), nullable=False),
        sa.Column("departure_start_date", sa.Date(), nullable=False),
        sa.Column("departure_end_date", sa.Date(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "MONITORING",
                "APPROACHING",
                "MATCHED",
                name="ticketstatus",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="prioritylevel",
                native_enum=False,
                length=50,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watch_tickets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_tickets")),
    )
    op.create_index(
        op.f("ix_watch_tickets_destination_iata"),
        "watch_tickets",
        ["destination_iata"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_tickets_origin_iata"),
        "watch_tickets",
        ["origin_iata"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_tickets_status"), "watch_tickets", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_watch_tickets_user_id"), "watch_tickets", ["user_id"], unique=False
    )
    op.create_table(
        "price_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("price_found", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["watch_tickets.id"],
            name=op.f("fk_price_logs_ticket_id_watch_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_logs")),
    )
    op.create_index(
        op.f("ix_price_logs_checked_at"), "price_logs", ["checked_at"], unique=False
    )
    op.create_index(
        op.f("ix_price_logs_ticket_id"), "price_logs", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_logs_ticket_id"), table_name="price_logs")
    op.drop_index(op.f("ix_price_logs_checked_at"), table_name="price_logs")
    op.drop_table("price_logs")
    op.drop_index(op.f("ix_watch_tickets_user_id"), table_name="watch_tickets")
    op.drop_index(op.f("ix_watch_tickets_status"), table_name="watch_tickets")
    op.drop_index(op.f("ix_watch_tickets_origin_iata"), table_name="watch_tickets")
    op.drop_index(op.f("ix_watch_tickets_destination_iata"), table_name="watch_tickets")
    op.drop_table("watch_tickets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
